% -------------------------------------------------------------------
%  Generated by MATLAB on 18-Dec-2019 20:20:42
%  MATLAB version: 9.7.0.1216025 (R2019b) Update 1
% -------------------------------------------------------------------
saveVarsMat = load('example_data_processing_wrkspce.mat');

mahan1 = saveVarsMat.mahan1; % <1057x5 double> too many elements

maly1 = saveVarsMat.maly1; % <1032x5 double> too many elements

maly2 = saveVarsMat.maly2; % <1026x5 double> too many elements

maly3 = saveVarsMat.maly3; % <1101x5 double> too many elements

nish1 = saveVarsMat.nish1; % <1017x5 double> too many elements

nish2 = saveVarsMat.nish2; % <1092x5 double> too many elements

nish3 = saveVarsMat.nish3; % <949x5 double> too many elements

single_sensor = saveVarsMat.single_sensor; % <1249x2 double> too many elements

unsure2 = saveVarsMat.unsure2; % <1089x5 double> too many elements

clear saveVarsMat;
